### ISSUE TITLE
[Task]: Switch "Duplicate Search" --> "Search for Issues"

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#116]
### Details

Should include:
- Name of activity
- Header of page
- State value in URL

Maybe should do in all the file names too.

p1681925679608289-slack-CQD1HH4MA

### Checklist

- [ ]

**Comment by karenroldan** [comment]
Taking a pause on this change! I think I'm in a rabbit hole and would need to take a step back... 😕  I created a draft PR that covers small changes on the naming: https://github.com/Automattic/bugomattic/pull/123 

I understand that we need to switch `Duplicate Search` to `Search for Issues`. For the file names and folder names, I decided to go for the naming `Issue Search` instead of `Search for Issues`. Mainly because there are names that follow `DuplicateSearching` and thought it will be more consistent to use `IssueSearching` instead! 

I did not touch/change the existing function names yet so it still all says `duplicateSearch`.
