### ISSUE TITLE
Unable to report bugs on Premium Themes through Bugomattic

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/bugomattic#196]
### Quick summary

When trying to report a bug on a Premium Theme this was happening:
![JRY2wbrv5lLKUCtqJdu8f4TwmXeXXHUoyYwHHBj7.jpg](https://github.com/user-attachments/assets/f2ce2e4e-2efe-4d2e-83eb-d54eaaa819e4)

### Steps to reproduce

1. Go to Bugomattic
2. Try to select Premium Automattic Themes in Step 2
3. Currently it does nothing
4. Previously it gave me the message above

### Browser

Google Chrome/Chromium

**Comment by jeherve** [comment]
Is this still happening for you right now? I'm wondering if it was a temporary fluke from GitHub. Or maybe I'm doing things wrong on my end, but I can't seem to reproduce the issue right now:


https://github.com/user-attachments/assets/e997a11c-38d8-4194-905c-2be889eed886

**Comment by dsas** [comment]
I fixed it a couple of hours ago in MC#157779, after @tanjoymor cleared her local storage the fix worked for her too.

**Comment by jeherve** [comment]
Ah, that makes sense. Turns out I had broken the bug report template a few days ago in https://github.com/Automattic/themes/pull/7997 ; this is what caused the bug report template not to work anymore. I fixed it in https://github.com/Automattic/themes/pull/8006, and then updated MC again to use the templates in 157791-ghe-Automattic/missioncontrol. We should be all set now!
